"""
SQLAlchemy models and database initialization for the Production Scheduler.
Uses SQLite with WAL mode for local pilot; swap DATABASE_URL for Postgres in prod.
"""

import os
from datetime import datetime
from sqlalchemy import (
    create_engine, Column, String, Integer, Float, Boolean,
    DateTime, Text, JSON, ForeignKey, Index
)
from sqlalchemy.orm import DeclarativeBase, sessionmaker, relationship
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./production_scheduler.db")

# Enable WAL mode for SQLite concurrency
connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}
engine = create_engine(
    DATABASE_URL,
    connect_args=connect_args,
    echo=False,
)

# Enable WAL mode on connect
if DATABASE_URL.startswith("sqlite"):
    from sqlalchemy import event
    @event.listens_for(engine, "connect")
    def set_wal_mode(dbapi_conn, connection_record):
        dbapi_conn.execute("PRAGMA journal_mode=WAL")
        dbapi_conn.execute("PRAGMA foreign_keys=ON")

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


# ─── Domain Models ───────────────────────────────────────────────────────────

class SalesHistory(Base):
    """Historical daily sales per SKU."""
    __tablename__ = "sales_history"

    id = Column(Integer, primary_key=True, index=True)
    sku = Column(String(50), nullable=False, index=True)
    date = Column(DateTime, nullable=False)
    quantity = Column(Float, nullable=False)
    is_promotional = Column(Boolean, default=False)
    region = Column(String(50), default="default")

    __table_args__ = (Index("ix_sales_sku_date", "sku", "date"),)


class MachineCapacity(Base):
    """Machine capacity per shift."""
    __tablename__ = "machine_capacity"

    id = Column(Integer, primary_key=True, index=True)
    machine_id = Column(String(50), nullable=False, index=True)
    machine_name = Column(String(100))
    shift = Column(Integer, nullable=False)          # 1, 2, or 3
    capacity_hours = Column(Float, nullable=False)   # hours available per shift
    utilization_pct = Column(Float, default=0.0)     # current utilization %
    compatible_skus = Column(JSON, default=list)     # list of SKUs this machine can process


class SKUMetadata(Base):
    """Product SKU metadata including display name and throughput rate."""
    __tablename__ = "sku_metadata"

    id = Column(Integer, primary_key=True, index=True)
    sku = Column(String(50), unique=True, nullable=False, index=True)
    display_name = Column(String(100), nullable=True)
    description = Column(String(255), nullable=True)
    units_per_hour = Column(Float, default=50.0)


class JobOrder(Base):
    """A production job order — the current schedule."""
    __tablename__ = "job_orders"

    id = Column(Integer, primary_key=True, index=True)
    job_id = Column(String(50), unique=True, nullable=False, index=True)
    job_name = Column(String(150), nullable=True)
    sku = Column(String(50), nullable=False, index=True)
    quantity = Column(Float, nullable=False)
    machine_id = Column(String(50), nullable=False)
    start_time = Column(DateTime, nullable=False)
    end_time = Column(DateTime, nullable=False)
    committed_delivery_date = Column(DateTime, nullable=True)
    has_committed_delivery = Column(Boolean, default=False)
    status = Column(String(30), default="scheduled")   # scheduled, in_progress, completed, cancelled
    priority = Column(Integer, default=5)              # 1 (highest) – 10 (lowest)
    margin_per_unit = Column(Float, default=1.0)       # for margin-weighted optimization
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class MaintenanceWindow(Base):
    """Planned maintenance / downtime per machine."""
    __tablename__ = "maintenance_windows"

    id = Column(Integer, primary_key=True, index=True)
    machine_id = Column(String(50), nullable=False, index=True)
    start_time = Column(DateTime, nullable=False)
    end_time = Column(DateTime, nullable=False)
    reason = Column(String(200))
    is_hard_constraint = Column(Boolean, default=True)  # hard = cannot schedule during


class ProposedChange(Base):
    """A proposed schedule change generated by the agent (not yet committed)."""
    __tablename__ = "proposed_changes"

    id = Column(Integer, primary_key=True, index=True)
    change_id = Column(String(50), unique=True, nullable=False, index=True)
    sku = Column(String(50))
    status = Column(String(20), default="pending")     # pending, approved, rejected, rolled_back
    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)

    # The actual before/after state
    before_state = Column(JSON)    # list of job orders before change
    after_state = Column(JSON)     # list of job orders after proposed change

    # Agent reasoning
    rationale = Column(Text)
    forecast_confidence = Column(String(10))   # high / medium / low
    has_delivery_date_warning = Column(Boolean, default=False)
    affected_jobs = Column(JSON, default=list)

    # Simulation results
    simulation_result = Column(JSON, nullable=True)

    # Approval info
    approved_by = Column(String(100), nullable=True)
    approved_at = Column(DateTime, nullable=True)
    rejected_by = Column(String(100), nullable=True)
    rejected_at = Column(DateTime, nullable=True)
    rejection_reason = Column(Text, nullable=True)


class AuditLog(Base):
    """Append-only audit log — every committed change is recorded here."""
    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True, index=True)
    change_id = Column(String(50), nullable=False, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False)
    actor = Column(String(100), nullable=False)   # "agent" or human planner name
    action = Column(String(50), nullable=False)   # commit, rollback, reject

    # Full before/after for rollback support
    before_state = Column(JSON)
    after_state = Column(JSON)

    # Context at decision time
    sku = Column(String(50))
    forecast_confidence = Column(String(10))
    has_delivery_date_warning = Column(Boolean, default=False)
    approval_status = Column(String(20))    # approved / rejected / rolled_back
    notes = Column(Text, nullable=True)

    __table_args__ = (Index("ix_audit_timestamp", "timestamp"),)


# ─── Helpers ─────────────────────────────────────────────────────────────────

def get_db():
    """FastAPI dependency — yields a DB session and closes it after the request."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def create_all_tables():
    """Create all tables and auto-migrate missing columns if necessary."""
    Base.metadata.create_all(bind=engine)
    
    # Auto-add columns if migrating an existing SQLite database
    with engine.connect() as conn:
        try:
            conn.execute(__import__("sqlalchemy").text("ALTER TABLE job_orders ADD COLUMN job_name VARCHAR(150)"))
            conn.commit()
        except Exception:
            pass
        try:
            conn.execute(__import__("sqlalchemy").text("ALTER TABLE machine_capacity ADD COLUMN machine_name VARCHAR(100)"))
            conn.commit()
        except Exception:
            pass
